# Generated by Django 4.1 on 2022-08-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, choices=[('BRKFAST', 'Breakfast'), ('LNCH', 'Lunch'), ('DNNR', 'Dinner'), ('SNCK', 'Snacks'), ('DRK', 'Drinks')], max_length=25)),
                ('add_menu', models.CharField(blank=True, max_length=25)),
                ('set_price', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rest_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('password', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('Non-B', 'Non-Binary')], max_length=25)),
                ('numberOfTable', models.IntegerField(default=0)),
            ],
        ),
    ]
