# Generated by Django 4.1 on 2022-08-16 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='shop_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='shop_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainAdmin.shop'),
        ),
    ]
