# Generated by Django 4.1 on 2022-08-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAdmin', '0002_remove_menu_shop_menu_menu_shop_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='mealtime',
            field=models.CharField(blank=True, choices=[('BRK', 'Breakfast'), ('LNCH', 'Lunch'), ('DNNR', 'Dinner'), ('Snk', 'Snack'), ('DRK', 'Drinks')], max_length=255),
        ),
    ]
